// Devnet addresses for the deployed AGC instance. Generated by
// `script/devnet-bootstrap.ts` on 2026-05-10 and committed here so the
// frontend bundle ships with them. Override per-environment via
// `VITE_SOLANA_*` env vars (e.g. for mainnet).
const DEVNET_ADDRESSES = {
  programId: "H1n8VTp6pMY5WFfVfi4MNkQ9q5szkMpVWcHQ21JRETXC",
  state: "2y2au7Fo1MEaXZzP8TknDrDfX2uezojkqaCxUBj6fMQS",
  agcMint: "BgEmfYvG48d93QHw5aBrRszdDobXTVPTdagg9fXwaP9D",
  xagcMint: "8N3f2iQVzUxh4k8CB2ZDzBy2HUn4wy1YMKVck63Hbbrz",
  usdcMint: "BCAw89QFbg1Zv7ZquAeKaCsF4t2V6FVCTQvDeK6Aawz9",
  btcMint: "DgqjKgCh3SnPhCEvEzpeLAviQLBk2VWsPSQEbekY87G2",
  treasuryAgc: "CfWtYbg4oJL3yWWCJscGL86U9Q5a57QMkHFmowxjdJ5R",
  treasuryUsdc: "J17zi2jdk4ManR47YQyT7t6Hxpq2xacrKrSsq2UH5o1T",
  xagcVaultAgc: "HJzwXgP3LJR8WbpxeVQDkK8ZBqmMrjoGk7zS8LRMUuSc",
  growthAgc: "GZNhA3oCKXHY6fnnTPrDaeAfsnHk8gPcMkUzJ4E7X71v",
  lpAgc: "BGdNpj31qpnrWLatzVS7z6aQ24rWQtRMiADZkqa8mgvj",
  integratorsAgc: "7oACqAQ6KuikHBDoEvqXJSKiRji79rvbXYrWVuZnJa8P",
  collateralAsset: "MpBeEH2t1k6wfRjcKcvZucapTx3nc9bivTtDnJ8iNVq",
  collateralOracle: "H5rGTPuDJoCVLkfUjqBJNN1yGsjxC1uQd2KYSdiacG65",
  facility: "ASJXw3NmVdPpkHVdrf6NXfRpChGDUeaHskEapNuHbmmq",
  underwriterVaultAgc: "3oV1UfH4wxQYcowk3MmfhwWLCBuJNmK1QKbKTSMfSoaV",
} as const;

const env = (key: string): string | undefined =>
  import.meta.env[`VITE_SOLANA_${key}` as keyof ImportMetaEnv] as string | undefined;

export const solanaCluster = env("CLUSTER") ?? "devnet";

export const solanaRpcUrl =
  env("RPC_URL") ??
  (solanaCluster === "mainnet-beta"
    ? "https://api.mainnet-beta.solana.com"
    : "https://api.devnet.solana.com");

export const solanaAddresses = {
  programId: env("PROGRAM_ID") ?? DEVNET_ADDRESSES.programId,
  state: env("STATE") ?? DEVNET_ADDRESSES.state,
  agcMint: env("AGC_MINT") ?? DEVNET_ADDRESSES.agcMint,
  xagcMint: env("XAGC_MINT") ?? DEVNET_ADDRESSES.xagcMint,
  usdcMint: env("USDC_MINT") ?? DEVNET_ADDRESSES.usdcMint,
  btcMint: env("BTC_MINT") ?? DEVNET_ADDRESSES.btcMint,
  treasuryAgc: env("TREASURY_AGC") ?? DEVNET_ADDRESSES.treasuryAgc,
  treasuryUsdc: env("TREASURY_USDC") ?? DEVNET_ADDRESSES.treasuryUsdc,
  xagcVaultAgc: env("XAGC_VAULT_AGC") ?? DEVNET_ADDRESSES.xagcVaultAgc,
  growthAgc: env("GROWTH_AGC") ?? DEVNET_ADDRESSES.growthAgc,
  lpAgc: env("LP_AGC") ?? DEVNET_ADDRESSES.lpAgc,
  integratorsAgc: env("INTEGRATORS_AGC") ?? DEVNET_ADDRESSES.integratorsAgc,
  collateralAsset: env("COLLATERAL_ASSET") ?? DEVNET_ADDRESSES.collateralAsset,
  collateralOracle: env("COLLATERAL_ORACLE") ?? DEVNET_ADDRESSES.collateralOracle,
  facility: env("FACILITY") ?? DEVNET_ADDRESSES.facility,
  underwriterVaultAgc:
    env("UNDERWRITER_VAULT_AGC") ?? DEVNET_ADDRESSES.underwriterVaultAgc,
};

// True once the protocol state + the two protocol-owned mints exist.
export const hasSolanaDeployment = Boolean(
  solanaAddresses.programId &&
    solanaAddresses.state &&
    solanaAddresses.agcMint &&
    solanaAddresses.xagcMint,
);

// True once the program bytecode is on a cluster, even if initialize_protocol
// has not yet been called. Lets the UI link to the program on the explorer.
export const hasProgramDeployment = Boolean(solanaAddresses.programId);

export function explorerProgramUrl(programId: string | undefined) {
  if (!programId) return null;
  const params = solanaCluster === "mainnet-beta" ? "" : `?cluster=${solanaCluster}`;
  return `https://explorer.solana.com/address/${programId}${params}`;
}

export function explorerAddressUrl(address: string | undefined) {
  if (!address) return null;
  const params = solanaCluster === "mainnet-beta" ? "" : `?cluster=${solanaCluster}`;
  return `https://explorer.solana.com/address/${address}${params}`;
}

// Jupiter swap only works against mainnet liquidity; the panel is hidden on
// other clusters to avoid a dead "connect wallet to swap" affordance.
export const showJupiterSwap = solanaCluster === "mainnet-beta";
